global:
  external_labels:
    monitor: devops_monitor
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - "localhost:9090"

  - job_name: node_cadvisor
    static_configs:
      - targets:
        - "ip address:8181"
  - job_name: node-exporter
    static_configs:
      - targets:
        - "ip address:9100"

  - job_name: 'blackbox'
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets: ['ip address:port']

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-icmp'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - ip address

        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115